kind: ConfigMap
apiVersion: v1
metadata:
  name: app-rhdh-config
data:
  app-config-rhdh.yaml: |
    app:
      title: My Red Hat Developer Hub
      baseUrl: https://developer-hub-utherp0-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com/
    proxy:
      endpoints:
        # customize developer hub instance
        /developer-hub:
          #target: https://raw.githubusercontent.com
          #target: http://backstage-customization-provider:8080
          target: http://provider3:8080
          #pathRewrite:
          #'^/api/proxy/developer-hub/tech-radar': /redhat-na-ssa/backstage-customization-provider/main/data/tech-radar/data.json
          #'^/api/proxy/developer-hub': /redhat-na-ssa/backstage-customization-provider/main/data/home/data.json
          changeOrigin: true
          secure: true
    integrations:
      github:
        - host: github.com
          token: githubtokenhere
    auth:
      allowGuestAccess: true
      environment: development
      providers:
        github:
          development:
            clientId: oauthclientdiehere
            clientSecret: oauthclientsecretehere
    enabled:
      github: true
